### ISSUE TITLE
[QUESTION] What is the purpose of this repo?

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/ef6tools#2]
Will all the runtime code be removed?

**Comment by ryanbrandenburg** [comment]
The purpose of this repo is to store the code for the EF6 and LINQ-To-SQL designers. Currently it lives in a branch on the ef6 repo, but the "master" branch of that repo had it (purposely) removed.

Yes, eventually we're planning to remove the runtime code and build it just off the NuGet versions of EF6, but some interdependency has built up over time so it's not quite as simple as just deleting the folders.
